env:
  browser: true
  es2021: true
parser: '@typescript-eslint/parser'
settings:
  react:
    version: detect
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - standard-with-typescript
  - prettier
overrides: []
ignorePatterns:
  - vite.config.ts
  - src/vite-env.d.ts
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
  - unused-imports
rules:
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  react/jsx-uses-react: off
  react/react-in-jsx-scope: off
  semi:
    - error
    - never
  import/order:
    [
      'error',
      {
        'groups':
          [
            'builtin',
            'external',
            'internal',
            'parent',
            'sibling',
            'index',
            'object',
            'type'
          ],
        'newlines-between': 'always',
        'pathGroupsExcludedImportTypes': ['builtin'],
        'alphabetize': { 'order': 'asc', 'caseInsensitive': true },
        'pathGroups': []
      }
    ]
  unused-imports/no-unused-imports: error
